config/routes.rb
Facebook::Application.routes.draw do
  resources :static_pages, only: [:index]
  resources :users do
    resources :notifications, only: [:index]
    resources :posts, except: [:show]
    resources :posts, only: [:show] do
      resources :comments, only: [:index, :create]
      resource :likes, only: [:create, :destroy]
    end
    resources :photos, only: [:new, :create, :index]
    resources :photos, only: [:show] do
      resources :comments, only: [:index, :create]
      resource :tags, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    resource :friend_request, only: [:create, :destroy]
    resources :friend_requests, only: [:index]
    resource :friendship, only: [:destroy]
  end
  resources :photos, only: [:destroy]
  resource :photos, only: [:create]
  resource :posts, only: [:create]
  resource :comments, only: [:create]
  resource :likes, only: [:create]
  resource :tags, only: [:create]
  resource :session, only: [:create, :destroy]
  delete 'posts/:id', to: "posts#destroy", as: "posts"
  delete 'photos/:id', to: "photos#destroy", as: "photos"
  delete 'comments/:id', to: "comments#destroy", as: "comments"
  delete 'likes/:id', to: "likes#destroy", as: "likes"
  delete 'tags/:id', to: "tags#destroy", as: "tags"
  root to: "static_pages#index"

  get 'demo', to: "sessions#demo"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    if logged_in?
      @user = User
        .includes(:received_posts)
        .find(current_user.id)

      @status = @user
        .status

      @posts = Post.all.reverse

      @users = current_user.friend_requesters.all
    else
      @user = User.new
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<% if logged_in? %>
<div class="profile">
  <%= render partial: "shared/profile", locals: {
      user: @user,
      status: @status
    } %>
</div>

 <div class="posts">
    <%= render partial: "shared/profile_nav", locals: {
      user: @user
    } %>
    <%= render partial: "shared/post_form", locals: {
        post: @post,
        user: @user,
        mode: "create",
        message: "Post"
      } %>
    <%= render partial: "shared/post", collection: @posts %>
 </div>

  <!-- <%= render partial: "shared/friend_requests", collection: @users, as: :user %> -->
<% else %>
<div class="splash group">
  <div class="splash-info">
    <div class="splash-info-text">
      <p class="pitch"><strong>Connect with friends on Ansiktebook</strong></p>
      <p class="more-info" style="text-align: center">Ansikte is Swedish for face  : )</p>
      <p class="info"><strong>See Photos and Posts</strong> from friends and family</p>
      <p class="info"><strong>Share what's new</strong> in your life</p>
      <p class="info"><strong>Find new friends</strong> in your network</p><br>
      <p class="more-info">Log in to a Twin Peaks-themed demo account here:</p>
    </div>
    <div class="demo-button">
      <a href="<%= demo_url %>">Demo</a>
    </div>
  </div>
  <%= render partial: "users/form", locals: {
    user: @user,
    mode: "create",
    action: users_url(@user),
    message: "Sign Up"
  } %>
</div>
<% end %>

<div id="content">
</div>