config/routes.rb
Facebook::Application.routes.draw do
  resources :static_pages, only: [:index]
  resources :users do
    resources :notifications, only: [:index]
    resources :posts, except: [:show]
    resources :posts, only: [:show] do
      resources :comments, only: [:index, :create]
      resource :likes, only: [:create, :destroy]
    end
    resources :photos, only: [:new, :create, :index]
    resources :photos, only: [:show] do
      resources :comments, only: [:index, :create]
      resource :tags, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    resource :friend_request, only: [:create, :destroy]
    resources :friend_requests, only: [:index]
    resource :friendship, only: [:destroy]
  end
  resources :photos, only: [:destroy]
  resource :photos, only: [:create]
  resource :posts, only: [:create]
  resource :comments, only: [:create]
  resource :likes, only: [:create]
  resource :tags, only: [:create]
  resource :session, only: [:create, :destroy]
  delete 'posts/:id', to: "posts#destroy", as: "posts"
  delete 'photos/:id', to: "photos#destroy", as: "photos"
  delete 'comments/:id', to: "comments#destroy", as: "comments"
  delete 'likes/:id', to: "likes#destroy", as: "likes"
  delete 'tags/:id', to: "tags#destroy", as: "tags"
  root to: "static_pages#index"

  get 'demo', to: "sessions#demo"
end

app/views/shared/_friend_requests.html.erb
<a href="<%= user_url(user) %>">
  <%= user.username %>
</a>
<img src="<%= user.profile_picture.url(:small) %>"
     height=75
     width=75>

<form action="<%= user_friend_request_url(user) %>"
      method="post">

    <input type="hidden"
           name="_method"
           value="delete">

    <%= auth_token %>

    <input type="hidden"
           name="status"
           value="approve">

    <input type="submit" value="Approve">
</form>

<form action="<%= user_friend_request_url(user) %>"
      method="post">

    <input type="hidden"
           name="_method"
           value="delete">

    <%= auth_token %>

    <input type="hidden"
           name="status"
           value="deny">

    <input type="submit" value="Deny">
</form>

app/views/shared/_like.html.erb
<%= like(likeable) %>

app/views/shared/_notification.html.erb
<%= parse_notification(notification) %></br>

app/views/shared/_photo.html.erb
<div class="photo-index">
  <% if link %>
    <a href="<%= user_photo_url(photo.user_id, photo.id) %>">
      <img src="<%= photo.filename.url(:small) %>">
    </a>
  <% else %>
    <a href="<%= user_photos_url(photo.user_id) %>">Back to Photos</a>
    <p>
      <img src="<%= photo.filename.url(:large) %>">
    </p>

    <p>
      at <%= time_ago_in_words photo.created_at %> ago
    </p>
    <p>
      <%= photo.likes.count %>
      <%= photo.likes.count == 1 ? "like" : "likes" %>
    </p>

    <% if photo.liked_by? current_user %>
      <form action="<%= user_photo_likes_url(current_user.id, photo.id) %>"
            method="post">
        <input type="hidden" name="_method" value="delete">
        <%= auth_token %>
        <input type="hidden" name="likeable_id" value="<%= photo.id %>">
        <input type="hidden" name="likeable_type" value="Photo">
        <input type="submit" value="Unlike">
      </form>
    <% else %>
      <form action="<%= user_photo_likes_url(current_user.id, photo.id) %>"
            method="post">
        <%= auth_token %>
        <input type="hidden" name="likeable_id" value="<%= photo.id %>">
        <input type="hidden" name="likeable_type" value="Photo">
        <input type="submit" value="Like">
      </form>
    <% end %>

    <% photo.tags.each do |tag| %>
      <% if tag.tagged == current_user ||
            tag.tagger == current_user ||
            photo.user == current_user %>
      <a href="<%= user_url(tag.tagged) %>">
        <%= tag.tagged.username %>
      </a>
        <%= button_to "Untag #{tag.tagged.username}",
                      user_photo_tags_url(tag.tagged_id, photo.id),
                      method: :delete %>
      <% else %>
      <a href="<%= user_url(tag.tagged) %>">
        <%= tag.tagged.username %>
      </a>
      <% end %>
    <% end %>

    <form action="<%= user_photo_tags_url(photo.user_id, photo.id) %>" method="post">
      <%= auth_token %>
      <select name="tagged_user_id">
        <option value="<%= current_user.id %>">
        <%= current_user.username %>
        </option>
        <% current_user.all_friends.each do |friend| %>
          <option value="<%= friend.id %>">
            <%= friend.username %>
          </option>
        <% end %>
      </select>
      <input type="submit" value="Tag a Friend">
    </form>

    <div class="photo-footer-item comments">
      <% photo.comments.each do |comment| %>
      <div class="photo-footer-item comment-item">
        <div class="group">
          <div class="comment-image">
            <img src="<%= comment.author.profile_picture.url(:small) %>"
                 height=75
                 width=75>
          </div>
          <div class="comment-content">
            <a href="<%= user_url(comment.author) %>">
              <strong><%= comment.author.username %></strong>
            </a>
            <p class="comment-text"><%= comment.body %></p>
          </div>
        </div>
        <div class="photo-footer-item comments delete-comment">
        <% if comment.author == current_user || photo.user == current_user %>
          <%= button_to "Delete", comment_url(comment), method: :delete %>
        <% end %>
        </div>
      </div>
      <% end %>
    </div>

    <div class="photo-footer-item comment">
      <form action="<%= user_photo_comments_url(current_user.id, photo.id) %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="comment[commentable_id]" value="<%= photo.id %>">
        <input type="hidden" name="comment[commentable_type]" value="Photo">
        <label for="post_comment">Add Comment</label>
        <input type="textarea" name="comment[body]" id="post_comment">
        <input type="submit" value="Comment">
      </form>
    </div>

    <% if photo.user == current_user %>
      <%= button_to "Delete", photo_url(photo), method: :delete %>
    <% end %>
  <% end %>
</div>

app/views/shared/_photo_form.html.erb
<form action="<%= user_photos_url %>"
      enctype="multipart/form-data"
      method="post">

  <%= auth_token %>

  <label for="photo_filename">Select a photo</label>
  <input type="file"
         name="photo[filename]"
         accept="image/*"
         id="photo_filename">

  <input type="submit"
         value="Upload">
</form>

app/views/shared/_post.html.erb
<div class="post">
  <div class="group">
    <div class="post-image">
      <img src="<%= post.author.profile_picture.url(:small) %>"
           height=75
           width=75>
    </div>
    <div class="post-content">
      <a href="<%= user_url(post.author) %>">
        <strong>
          <%= post.author.username %>
        </strong>
      </a>
    <% unless post.author == post.recipient %>
      <strong>
        >
      </strong>
      <a href="<%= user_url(post.recipient) %>">
        <strong>
          <%= post.recipient.username %>
        </strong>
      </a>
    <% end %>
      <p class="post-text">
        <%= post.text %>
      </p>
    </div>
  </div>

  <div class="post-footer">
    <div class="likes <%= "can-like" unless post.liked_by?(current_user) %>">
      <div class="unlike ">
        <%= unlike(post) %>
      </div>
      <div class="like">
        <%= like(post) %>
      </div>
    </div>

    <div class="post-footer-item">
      posted <%= time_ago_in_words post.created_at %> ago
    </div>

    <div class="post-footer-item">
      <%= post.likes.count %>
      <%= post.likes.count == 1 ? "like" : "likes" %>
    </div>

    <% post.comments.each do |comment| %>
      <div class="group">
        <div class="comment-image">
          <img src="<%= comment.author.profile_picture.url(:small) %>"
               height=75
               width=75>
        </div>
        <div class="comment-content">
          <a href="<%= user_url(comment.author) %>">
            <strong>
              <%= comment.author.username %>
            </strong>
          </a>
          <div class="comment-text">
            <%= comment.body %>
          </div>
        </div>
      <div class="post-footer-item comments delete-comment">
      <% if comment.author == current_user || post.recipient == current_user %>
        <%= button_to "Delete", comments_url(comment), method: :delete %>
      <% end %>
      </div>
    </div>
    <% end %>

    <div class="post-footer-item comment">
      <form action="<%= user_post_comments_url(current_user.id, post.id) %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="comment[commentable_id]" value="<%= post.id %>">
        <input type="hidden" name="comment[commentable_type]" value="Post">
        <input type="textarea" name="comment[body]" id="post_comment">
        <input type="submit" value="Comment">
      </form>
    </div>

    <div class="post-footer-item edit">
    <div class="edit-or-delete-comment">
    <% if post.author == current_user %>
      <%= button_to "Edit",
                    edit_user_post_url(post.recipient_id, post),
                    method: :get %>
      <%= button_to "Delete", user_post_url(post.recipient_id, post), method: :delete %>
    <% elsif post.recipient == current_user %>
      <%= button_to "Delete",
                    user_post_url(post.recipient_id, post),
                    method: :delete %>
    <% end %>
    </div>
    </div>
  </div>
</div>

app/views/shared/_post_form.html.erb
<div class="post-form">
<% if mode == "update"  %>
  <% action = user_post_url(current_user, post) %>
<% elsif mode == "create" %>
  <% action = user_posts_url(user, post) %>
<% end %>

<form action="<%= action %>" method="post">

  <% if mode == "update" %>
    <input type="hidden" name="_method" value="put">
  <% end %>

  <%= auth_token %>
  <input type="textarea"
           name="post[text]"
           id="post_text">
  <input type="submit"
         value="<%= message %>">

</form>
<% if mode == "update"  %>
  <%= button_to "Delete Post", user_post_url(current_user, post), method: :delete %>
<% end %>
</div>

app/views/shared/_profile.html.erb
<img src="<%= user.profile_picture.url(:large) %>"
   height=300
   width=300>

<table>
<tr>
  <td>Email</td>
  <td><%= user.email %></td>
</tr>
<tr>
  <td>Birthday</td>
  <td><%= user.birthday %></td>
</tr>
</table>
<div class="about">
<%= user.about %>
</div>

app/views/shared/_profile_nav.html.erb
<div class="status">
  <strong>
    <%= user.username %>
  </strong>
    <%= user.status.text if user.status %>

<% if user != current_user %>

  <% if current_user.is_friend?(user) %>
    <form action="<%= user_friendship_url(user) %>" method="post">

      <input type="hidden"
             name="_method"
             value="delete">

      <%= auth_token %>

      <input type="hidden"
             name="friend_id"
             value="<%= user.id %>">

      <input type="submit"
             value="Unfriend">
    </form>
  <% elsif !current_user.sent_friend_request?(user) %>
    <form action="<%= user_friend_request_url(user) %>" method="post">

      <%= auth_token %>

      <input type="hidden"
             name="recipient_id"
             value="<%= user.id %>">

      <input type="submit"
             value="Friend Request">
    </form>

  <% else %>
  Friend request pending...

  <% end %>

<% else %>

<% end %>

</div>

<div class="group">
  <div class="profile-nav-item">
    <a href="<%= user_url(user) %>">Profile</a>
  </div>
  <div class="profile-nav-item">
    <a href="<%= user_photos_url(user) %>">Photos</a>
  </div>
</div>

app/views/shared/_unlike.html.erb
<%= unlike(likeable) %>