config/routes.rb
Facebook::Application.routes.draw do
  resources :static_pages, only: [:index]
  resources :users do
    resources :notifications, only: [:index]
    resources :posts, except: [:show]
    resources :posts, only: [:show] do
      resources :comments, only: [:index, :create]
      resource :likes, only: [:create, :destroy]
    end
    resources :photos, only: [:new, :create, :index]
    resources :photos, only: [:show] do
      resources :comments, only: [:index, :create]
      resource :tags, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end
    resource :friend_request, only: [:create, :destroy]
    resources :friend_requests, only: [:index]
    resource :friendship, only: [:destroy]
  end
  resources :photos, only: [:destroy]
  resource :photos, only: [:create]
  resource :posts, only: [:create]
  resource :comments, only: [:create]
  resource :likes, only: [:create]
  resource :tags, only: [:create]
  resource :session, only: [:create, :destroy]
  delete 'posts/:id', to: "posts#destroy", as: "posts"
  delete 'photos/:id', to: "photos#destroy", as: "photos"
  delete 'comments/:id', to: "comments#destroy", as: "comments"
  delete 'likes/:id', to: "likes#destroy", as: "likes"
  delete 'tags/:id', to: "tags#destroy", as: "tags"
  root to: "static_pages#index"

  get 'demo', to: "sessions#demo"
end

app/views/layouts/_errors.html.erb
<div class="flashes">
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>

      <strong class="errors"><%= error %></strong><br>

    <% end %>
  <% end %>

  <% if flash[:notices] %>
    <% flash[:notices].each do |notice| %>

      <strong class="notices"><%= notice %></strong><br>

    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<% if logged_in? %>
  <div class="navbar logged-in">
    <a href="<%= static_pages_url %>" class="logo">Ansiktebook</a>
    <!-- <a href="<%= users_url %>">Users</a> -->
    <div class="top-right">
	  <div class="top-right-item">
      	<a href="<%= user_friend_requests_url(current_user) %>">Requests</a>
  	  </div>
	  <div class="top-right-item notifications-button">
      	<a href="<%= user_notifications_url(current_user) %>">Notifications</a>
        <div class="new-notifications"></div>
	  </div>
	  <div class="top-right-item">
        <a href="<%= edit_user_url(current_user) %>">Settings</a>
	  </div>
	  <div class="top-right-item">
      	<%= button_to "Sign Out", session_url, method: :delete %>
	  </div>
    </div>
  </div>
<% else %>
  <div class="navbar logged-out">
    <a href="<%= static_pages_url %>">Ansiktebook</a>
    <div class="login">
    <form action="<%= session_url %>" method="post">

      <%= auth_token %>
      <div class="email">
      <label for="user_email">Email</label>
      <input type="email"
             name="user[email]"
             value="<%= @user.email %>"
             id="user_username">
      </div>

      <div class="password">
      <label for="user_password">Password</label>
      <input type="password"
             name="user[password]"
             id="user_password">
      </div>

      <input type="submit"
             value="Sign In">
    </form>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ansiktebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <style>

  </style>
</head>
<body>
  <div class="navbar-wrapper">
  	<div class="navbar">
  	  <%= render "layouts/navigation", object: @user %>
  	</div>
  </div>
  <div class="errors">
    <%= render "layouts/errors" %>
  </div>

  <div class="wrapper group">
    <%= yield %>
  </div>

  <% if logged_in? %>
  <script>
    $(document).ready(function(){
      event.preventDefault();
      Facebook.initialize();
      $('body').css('background', '#ECEFF4')

      $('.notifications-button').on("click", function(event) {
        event.preventDefault();
        $('.notifications').toggleClass('show-notifications');
      });
    });
  </script>
  <% end %>
</body>
</html>